FROM  node:20.18.0-alpine3.20
ENV DB_HOST="mysql"
EXPOSE  8080
# opt is opptional
# and you are moving to this directory /opt/server so we are using workdir command  
RUN  mkdir /opt/server 
WORKDIR  /opt/server
# copy will copy all the code 
COPY   package.json .
COPY  *.js .
# rest all js files will be copy here.
RUN npm install
CMD ["node", "index.js"]


#Before best-practices implemented

# FROM  node:20
# ENV DB_HOST="mysql"
# EXPOSE  8080
# # opt is opptional
# # and you are moving to this directory /opt/server so we are using workdir command  
# RUN  mkdir /opt/server 
# WORKDIR  /opt/server
# # copy will copy all the code 
# COPY   package.json .
# COPY  *.js .
# # rest all js files will be copy here.
# RUN npm install
# CMD ["node", "index.js"]


